export const Permission = {
  HR_READ: "hr.read",
  HR_DIRECTORY_READ: "hr.directory.read",
  HR_REQUEST_CREATE: "hr.request.create",
  HR_CREATE: "hr.create",
  HR_UPDATE: "hr.update",
  ATTENDANCE_READ: "attendance.read",
  ATTENDANCE_CREATE: "attendance.create",
  CLIENT_READ: "client.read",
  CLIENT_CREATE: "client.create",
  CLIENT_UPDATE: "client.update",
  DEPARTMENT_READ: "department.read",
  DEPARTMENT_CREATE: "department.create",
  DEPARTMENT_UPDATE: "department.update",
  CONTRACT_READ: "contract.read",
  CONTRACT_CREATE: "contract.create",
  CONTRACT_UPDATE: "contract.update",
  CONTRACT_EMIT: "contract.emit",
  CONTRACT_SIGN: "contract.sign",
  CONTRACT_CANCEL: "contract.cancel",
  DOCUMENT_READ: "document.read",
  DOCUMENT_DOWNLOAD: "document.download",
  ACTIVITY_READ: "activity.read",
  AUDIT_READ: "audit.read",
  TEMPLATE_READ: "template.read",
  TEMPLATE_MANAGE: "template.manage",
  INTEGRATION_READ: "integration.read",
  INTEGRATION_MANAGE: "integration.manage",
  WEB_CONTENT_READ: "web_content.read",
  WEB_CONTENT_UPDATE: "web_content.update",
  USER_READ: "user.read",
  USER_MANAGE: "user.manage",
  ROLE_MANAGE: "role.manage",
  USER_DELETE: "user.delete",
  PERMISSION_REQUEST_CREATE: "permission_request.create",
  PERMISSION_REQUEST_READ: "permission_request.read",
  PERMISSION_REQUEST_APPROVE: "permission_request.approve",
  WORK_ORDER_READ: "work_order.read",
  WORK_ORDER_CREATE: "work_order.create",
  WORK_ORDER_UPDATE: "work_order.update",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

export const PERMISSIONS: Permission[] = Object.values(Permission);

export const PERMISSION_DESCRIPTIONS: Record<Permission, string> = {
  [Permission.HR_READ]: "Ver expedientes y estructura de Recursos Humanos",
  [Permission.HR_DIRECTORY_READ]: "Ver nombres y cargo del directorio laboral",
  [Permission.HR_REQUEST_CREATE]: "Solicitar vacaciones o permisos propios",
  [Permission.HR_CREATE]: "Crear expedientes de Recursos Humanos",
  [Permission.HR_UPDATE]: "Editar y finalizar expedientes de Recursos Humanos",
  [Permission.ATTENDANCE_READ]: "Ver el cronograma de asistencia",
  [Permission.ATTENDANCE_CREATE]: "Marcar entrada, refrigerio y salida",
  [Permission.CLIENT_READ]: "Ver clientes",
  [Permission.CLIENT_CREATE]: "Crear clientes",
  [Permission.CLIENT_UPDATE]: "Editar clientes",
  [Permission.DEPARTMENT_READ]: "Ver departamentos",
  [Permission.DEPARTMENT_CREATE]: "Crear departamentos",
  [Permission.DEPARTMENT_UPDATE]: "Editar departamentos",
  [Permission.CONTRACT_READ]: "Ver contratos",
  [Permission.CONTRACT_CREATE]: "Crear contratos",
  [Permission.CONTRACT_UPDATE]: "Editar contratos",
  [Permission.CONTRACT_EMIT]: "Emitir contratos",
  [Permission.CONTRACT_SIGN]: "Solicitar y registrar firma de contratos",
  [Permission.CONTRACT_CANCEL]: "Cancelar contratos",
  [Permission.DOCUMENT_READ]: "Ver documentos",
  [Permission.DOCUMENT_DOWNLOAD]: "Descargar documentos",
  [Permission.ACTIVITY_READ]: "Ver actividad",
  [Permission.AUDIT_READ]: "Ver auditoría",
  [Permission.TEMPLATE_READ]: "Ver plantillas",
  [Permission.TEMPLATE_MANAGE]: "Gestionar plantillas",
  [Permission.INTEGRATION_READ]: "Ver integraciones",
  [Permission.INTEGRATION_MANAGE]: "Gestionar integraciones",
  [Permission.WEB_CONTENT_READ]: "Ver contenido web",
  [Permission.WEB_CONTENT_UPDATE]: "Editar contenido web",
  [Permission.USER_READ]: "Ver usuarios",
  [Permission.USER_MANAGE]: "Gestionar usuarios",
  [Permission.ROLE_MANAGE]: "Gestionar roles",
  [Permission.USER_DELETE]: "Eliminar usuarios (solo Developer)",
  [Permission.PERMISSION_REQUEST_CREATE]: "Solicitar permiso al Developer",
  [Permission.PERMISSION_REQUEST_READ]: "Ver solicitudes de permiso",
  [Permission.PERMISSION_REQUEST_APPROVE]: "Aprobar o rechazar solicitudes de permiso",
  [Permission.WORK_ORDER_READ]: "Ver órdenes de trabajo",
  [Permission.WORK_ORDER_CREATE]: "Crear órdenes de trabajo",
  [Permission.WORK_ORDER_UPDATE]: "Asignar y actualizar órdenes de trabajo",
};
