export const Permission = {
  CLIENT_READ: "client.read",
  CLIENT_CREATE: "client.create",
  CLIENT_UPDATE: "client.update",
  DEPARTMENT_READ: "department.read",
  DEPARTMENT_CREATE: "department.create",
  DEPARTMENT_UPDATE: "department.update",
  CONTRACT_READ: "contract.read",
  CONTRACT_CREATE: "contract.create",
  CONTRACT_UPDATE: "contract.update",
  CONTRACT_EMIT: "contract.emit",
  CONTRACT_SIGN: "contract.sign",
  CONTRACT_CANCEL: "contract.cancel",
  DOCUMENT_READ: "document.read",
  DOCUMENT_DOWNLOAD: "document.download",
  ACTIVITY_READ: "activity.read",
  AUDIT_READ: "audit.read",
  TEMPLATE_READ: "template.read",
  TEMPLATE_MANAGE: "template.manage",
  INTEGRATION_READ: "integration.read",
  INTEGRATION_MANAGE: "integration.manage",
  USER_READ: "user.read",
  USER_MANAGE: "user.manage",
  ROLE_MANAGE: "role.manage",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

export const PERMISSIONS: Permission[] = Object.values(Permission);

export const PERMISSION_DESCRIPTIONS: Record<Permission, string> = {
  [Permission.CLIENT_READ]: "Ver clientes",
  [Permission.CLIENT_CREATE]: "Crear clientes",
  [Permission.CLIENT_UPDATE]: "Editar clientes",
  [Permission.DEPARTMENT_READ]: "Ver departamentos",
  [Permission.DEPARTMENT_CREATE]: "Crear departamentos",
  [Permission.DEPARTMENT_UPDATE]: "Editar departamentos",
  [Permission.CONTRACT_READ]: "Ver contratos",
  [Permission.CONTRACT_CREATE]: "Crear contratos",
  [Permission.CONTRACT_UPDATE]: "Editar contratos",
  [Permission.CONTRACT_EMIT]: "Emitir contratos",
  [Permission.CONTRACT_SIGN]: "Solicitar y registrar firma de contratos",
  [Permission.CONTRACT_CANCEL]: "Cancelar contratos",
  [Permission.DOCUMENT_READ]: "Ver documentos",
  [Permission.DOCUMENT_DOWNLOAD]: "Descargar documentos",
  [Permission.ACTIVITY_READ]: "Ver actividad",
  [Permission.AUDIT_READ]: "Ver auditoría",
  [Permission.TEMPLATE_READ]: "Ver plantillas",
  [Permission.TEMPLATE_MANAGE]: "Gestionar plantillas",
  [Permission.INTEGRATION_READ]: "Ver integraciones",
  [Permission.INTEGRATION_MANAGE]: "Gestionar integraciones",
  [Permission.USER_READ]: "Ver usuarios",
  [Permission.USER_MANAGE]: "Gestionar usuarios",
  [Permission.ROLE_MANAGE]: "Gestionar roles",
};